"""Runner for COMSOL C02 MATLAB model construction smoke."""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path
from typing import Any

from .config import load_case_config, repo_relative_path, validate_case_config
from .report import write_validation_report
from .validation import (
    duplicate_tag_count,
    finite_parameter_count,
    load_json_artifact,
    missing_required_tags,
    summarize_environment_checks,
    validate_metrics,
)

SCHEMA_ID = "schemas/comsol_C02_model_construction_api_contract.schema.json"


def _matlab_string(value: str) -> str:
    return str(value).replace("'", "''")


def _env_path_check(env_name: str, required: bool, path_kind: str) -> dict[str, Any]:
    value = os.environ.get(env_name)
    configured = bool(value)
    exists = False
    if configured:
        path = Path(str(value))
        exists = path.is_file() if path_kind == "file" else path.is_dir()
    return {
        "env": env_name,
        "required": required,
        "path_kind": path_kind,
        "configured": configured,
        "exists": exists,
    }


def _collect_environment(config: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        _env_path_check(config["matlab"]["executable_env"], True, "file"),
        _env_path_check(config["comsol"]["command_env"], True, "file"),
        _env_path_check(config["livelink"]["mli_dir_env"], True, "directory"),
        _env_path_check(config["comsol"]["mphserver_env"], False, "file"),
    ]


def _parameter_script_lines(config: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    for parameter in config["model_tree"]["parameters"]:
        name = _matlab_string(parameter["name"])
        expression = _matlab_string(parameter["expression"])
        lines.append(f"model.param.set('{name}', '{expression}');")
    return lines


def _parameter_evaluation_lines(config: dict[str, Any]) -> list[str]:
    lines = ["parameterValues = struct();"]
    for parameter in config["model_tree"]["parameters"]:
        name = _matlab_string(parameter["name"])
        value_var = f"value_{parameter['name']}"
        numeric_var = f"numeric_{parameter['name']}"
        lines.extend(
            [
                f"{value_var} = mphevaluate(model, '{name}');",
                f"if isnumeric({value_var})",
                f"    {numeric_var} = {value_var}(1);",
                "else",
                f"    {numeric_var} = str2double(char({value_var}));",
                "end",
                f"parameterValues.{name} = {numeric_var};",
            ]
        )
    return lines


def _script_text(config: dict[str, Any]) -> str:
    tags = config["model_tree"]["tags"]
    geometry = config["model_tree"]["geometry"]
    mesh = config["model_tree"]["mesh"]
    study = config["model_tree"]["study"]
    tag_lines = [
        f"modelTag = '{_matlab_string(tags['model_tag'])}';",
        f"componentTag = '{_matlab_string(tags['component_tag'])}';",
        f"geometryTag = '{_matlab_string(tags['geometry_tag'])}';",
        f"materialTag = '{_matlab_string(tags['material_tag'])}';",
        f"meshTag = '{_matlab_string(tags['mesh_tag'])}';",
        f"studyTag = '{_matlab_string(tags['study_tag'])}';",
        f"rectangleTag = '{_matlab_string(geometry['feature_tag'])}';",
        f"studyFeatureTag = '{_matlab_string(study['feature_tag'])}';",
    ]
    api_calls = [
        "ModelUtil.create",
        "model.param.set",
        "component.create",
        "geom.create",
        "geom.feature.create",
        "geom.run",
        "material.create",
        "mesh.create",
        "study.create",
        "mphevaluate",
    ]
    api_cell = "{" + ", ".join(f"'{_matlab_string(item)}'" for item in api_calls) + "}"
    required_tags = config["validation"]["required_tags"]
    required_tag_cell = "{" + ", ".join(f"'{_matlab_string(item)}'" for item in required_tags) + "}"
    size_params = geometry["size_parameters"]
    return "\n".join(
        [
            "% Generated by science-capability-registry COMSOL C02.",
            "% This script constructs a model tree only; it must not run a study solve.",
            "mliDir = getenv('COMSOL_MLI_DIR');",
            "if strlength(mliDir) > 0",
            "    addpath(mliDir);",
            "end",
            "import com.comsol.model.*",
            "import com.comsol.model.util.*",
            "host = getenv('COMSOL_SERVER_HOST');",
            "portText = getenv('COMSOL_SERVER_PORT');",
            "if strlength(host) > 0",
            "    if strlength(portText) > 0",
            "        mphstart(host, str2double(portText));",
            "    else",
            "        mphstart(host);",
            "    end",
            "end",
            *tag_lines,
            "try",
            "    ModelUtil.remove(modelTag);",
            "catch",
            "end",
            "model = ModelUtil.create(modelTag);",
            *_parameter_script_lines(config),
            "model.component.create(componentTag, true);",
            "model.component(componentTag).geom.create(geometryTag, 2);",
            f"model.component(componentTag).geom(geometryTag).create(rectangleTag, '{_matlab_string(geometry['feature_type'])}');",
            f"model.component(componentTag).geom(geometryTag).feature(rectangleTag).set('size', {{'{_matlab_string(size_params[0])}', '{_matlab_string(size_params[1])}'}});",
            "model.component(componentTag).geom(geometryTag).run;",
            f"model.component(componentTag).material.create(materialTag, '{_matlab_string(config['model_tree']['material']['material_type'])}');",
            "model.component(componentTag).mesh.create(meshTag);",
            f"model.component(componentTag).mesh(meshTag).autoMeshSize({int(mesh['auto_mesh_size'])});",
            "model.study.create(studyTag);",
            f"model.study(studyTag).create(studyFeatureTag, '{_matlab_string(study['study_type'])}');",
            *_parameter_evaluation_lines(config),
            "declaredTags = struct();",
            "declaredTags.model_tag = modelTag;",
            "declaredTags.component_tag = componentTag;",
            "declaredTags.geometry_tag = geometryTag;",
            "declaredTags.material_tag = materialTag;",
            "declaredTags.mesh_tag = meshTag;",
            "declaredTags.study_tag = studyTag;",
            "retrieval = struct();",
            "retrieval.model_created = true;",
            "retrieval.component_created = true;",
            "retrieval.geometry_created = true;",
            "retrieval.material_created = true;",
            "retrieval.mesh_created = true;",
            "retrieval.study_created = true;",
            "modelTree = struct();",
            "modelTree.declared_tags = declaredTags;",
            "modelTree.parameter_values = parameterValues;",
            "modelTree.parameter_names = fieldnames(parameterValues);",
            "modelTree.required_tags = " + required_tag_cell + ";",
            "modelTree.retrieval = retrieval;",
            "modelTree.solver_executed = false;",
            "construction = struct();",
            f"construction.backend = '{_matlab_string(config['backend']['type'])}';",
            "construction.generated_script = 'matlab_model_construction_smoke.m';",
            "construction.api_calls = " + api_cell + ";",
            "construction.no_claims = {'no study solve', 'no physics validation', 'no official model replay'};",
            "construction.solver_executed = false;",
            "fid = fopen('model_tree_manifest.json', 'w');",
            "fprintf(fid, '%s\\n', jsonencode(modelTree));",
            "fclose(fid);",
            "fid = fopen('construction_manifest.json', 'w');",
            "fprintf(fid, '%s\\n', jsonencode(construction));",
            "fclose(fid);",
            "ModelUtil.remove(modelTag);",
            "",
        ]
    )


def _write_script(config: dict[str, Any], output_dir: Path) -> Path:
    script_path = output_dir / config["model_tree"]["script_filename"]
    script_path.write_text(_script_text(config), encoding="ascii")
    return script_path


def _write_placeholders(output_dir: Path, message: str) -> None:
    for name in ["stdout.txt", "stderr.txt"]:
        (output_dir / name).write_text(message + "\n", encoding="utf-8")


def _execute_matlab(config: dict[str, Any], output_dir: Path, script_path: Path) -> int:
    matlab_exe = Path(os.environ[config["matlab"]["executable_env"]])
    stdout_path = output_dir / "stdout.txt"
    stderr_path = output_dir / "stderr.txt"
    script_expr = f"run('{script_path.resolve().as_posix()}')"
    with stdout_path.open("w", encoding="utf-8", errors="replace") as stdout, stderr_path.open(
        "w", encoding="utf-8", errors="replace"
    ) as stderr:
        result = subprocess.run(
            [str(matlab_exe), config["matlab"]["batch_argument"], script_expr],
            cwd=output_dir,
            stdout=stdout,
            stderr=stderr,
            timeout=float(config["backend"]["timeout_s"]),
            check=False,
        )
    return result.returncode


def _build_metrics(
    config: dict[str, Any],
    output_dir: Path,
    script_path: Path,
    environment_checks: list[dict[str, Any]],
    dry_run: bool,
    matlab_return_code: int | None,
) -> dict[str, Any]:
    model_tree = load_json_artifact(output_dir / "model_tree_manifest.json")
    construction = load_json_artifact(output_dir / "construction_manifest.json")
    env_summary = summarize_environment_checks(environment_checks)
    missing_tags = [] if dry_run else missing_required_tags(config, model_tree)
    parameter_count = len(config["model_tree"]["parameters"])
    finite_count = finite_parameter_count(config, model_tree)
    solver_executed = bool(model_tree.get("solver_executed")) if model_tree is not None else False
    if dry_run:
        runtime_status = "dry_run_not_executed"
    elif config["backend"]["type"] == "preflight_only":
        runtime_status = "env_preflight_passed_no_matlab_execution" if env_summary["all_required_paths_exist"] else "blocked_by_runtime_profile"
    elif matlab_return_code is None:
        runtime_status = "blocked_by_runtime_profile"
    elif matlab_return_code == 0 and model_tree is not None and construction is not None and not missing_tags and finite_count == parameter_count:
        runtime_status = "matlab_livelink_model_tree_passed"
    else:
        runtime_status = "matlab_livelink_model_tree_failed"
    return {
        "capability_id": config["capability_id"],
        "case_id": config["case_id"],
        "validated_config": True,
        "script_generated": script_path.exists(),
        "script_file": script_path.name,
        "environment_checks": environment_checks,
        "environment_summary": env_summary,
        "matlab_executed": matlab_return_code is not None,
        "matlab_return_code": matlab_return_code,
        "model_tree_manifest_written": model_tree is not None,
        "construction_manifest_written": construction is not None,
        "parameter_count": parameter_count,
        "finite_parameter_count": finite_count,
        "component_count": 1 if model_tree is not None else 0,
        "required_tag_missing_count": len(missing_tags),
        "missing_required_tags": missing_tags,
        "duplicate_tag_count": duplicate_tag_count(config),
        "solver_executed": solver_executed,
        "runtime_status": runtime_status,
    }


def _build_manifest(config: dict[str, Any], output_dir: Path, generated_files: list[str], metrics: dict[str, Any], validation: dict[str, Any]) -> dict[str, Any]:
    return {
        "capability_id": config["capability_id"],
        "case_id": config["case_id"],
        "source_config": config.get("_config_path"),
        "schema_id": SCHEMA_ID,
        "validated_config": True,
        "output_dir": str(output_dir),
        "runtime_profile": config["comsol"]["runtime_profile"],
        "runtime_profile_config": config["comsol"]["runtime_profile_config"],
        "backend": config["backend"],
        "model_tree": config["model_tree"],
        "generated_files": generated_files,
        "expected_outputs": config["outputs"]["expected_outputs"],
        "metrics": metrics,
        "validation": validation,
        "scope": validation["scope"],
    }


def run(
    config_path: str | Path | None = None,
    config: dict[str, Any] | None = None,
    output_dir: str | Path | None = None,
    dry_run: bool = False,
    backend: str | None = None,
) -> dict[str, Any]:
    if config is None:
        if config_path is None:
            raise ValueError("Either config_path or config must be provided.")
        config = load_case_config(config_path)
    else:
        config = validate_case_config(config)
    if backend is not None:
        config = {**config, "backend": {**config["backend"], "type": backend}}
        config = validate_case_config(config)

    output_path = Path(output_dir) if output_dir is not None else repo_relative_path(config["outputs"]["output_dir"])
    output_path.mkdir(parents=True, exist_ok=True)
    script_path = _write_script(config, output_path)
    environment_checks = _collect_environment(config)
    env_summary = summarize_environment_checks(environment_checks)
    matlab_return_code: int | None = None
    generated_files = [
        config["model_tree"]["script_filename"],
        "stdout.txt",
        "stderr.txt",
        "metrics.json",
        "validation.json",
        "validation_report.md",
        "manifest.json",
    ]
    backend_type = config["backend"]["type"]
    if dry_run or backend_type == "dry_run_only":
        _write_placeholders(output_path, "dry-run placeholder; MATLAB and COMSOL were not executed.")
    elif backend_type == "preflight_only":
        _write_placeholders(output_path, "preflight-only placeholder; MATLAB and COMSOL were not executed.")
    elif backend_type == "matlab_livelink_model_tree_smoke":
        if env_summary["all_required_paths_exist"]:
            matlab_return_code = _execute_matlab(config, output_path, script_path)
            for name in ["model_tree_manifest.json", "construction_manifest.json"]:
                if (output_path / name).exists():
                    generated_files.append(name)
        else:
            _write_placeholders(output_path, "runtime profile is incomplete; MATLAB and COMSOL were not executed.")
    else:
        raise NotImplementedError(f"COMSOL C02 backend {backend_type!r} is not implemented.")

    metrics = _build_metrics(config, output_path, script_path, environment_checks, dry_run, matlab_return_code)
    validation = validate_metrics(metrics, config, output_path, check_artifacts=False)
    (output_path / "metrics.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    (output_path / "validation.json").write_text(json.dumps(validation, indent=2), encoding="utf-8")
    write_validation_report(output_path / "validation_report.md", config, metrics, validation)
    manifest = _build_manifest(config, output_path, generated_files, metrics, validation)
    (output_path / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    validation = validate_metrics(metrics, config, output_path, check_artifacts=True)
    manifest["validation"] = validation
    manifest["scope"] = validation["scope"]
    (output_path / "validation.json").write_text(json.dumps(validation, indent=2), encoding="utf-8")
    write_validation_report(output_path / "validation_report.md", config, metrics, validation)
    (output_path / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest


def run_from_config(config_path: str | Path, output_dir: str | Path | None = None) -> dict[str, Any]:
    return run(config_path=config_path, output_dir=output_dir, dry_run=True)
