"""Runner for COMSOL C01 MATLAB server bridge preflight."""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path
from typing import Any

from .config import load_case_config, repo_relative_path, validate_case_config
from .report import write_validation_report
from .validation import parse_scalar_file, summarize_environment_checks, validate_metrics

SCHEMA_ID = "schemas/comsol_C01_matlab_server_bridge_runtime.schema.json"


def _env_path_check(env_name: str, required: bool, path_kind: str) -> dict[str, Any]:
    value = os.environ.get(env_name)
    configured = bool(value)
    exists = False
    if configured:
        path = Path(str(value))
        exists = path.is_file() if path_kind == "file" else path.is_dir()
    return {
        "env": env_name,
        "required": required,
        "path_kind": path_kind,
        "configured": configured,
        "exists": exists,
    }


def _collect_environment(config: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        _env_path_check(config["matlab"]["executable_env"], True, "file"),
        _env_path_check(config["comsol"]["command_env"], True, "file"),
        _env_path_check(config["livelink"]["mli_dir_env"], True, "directory"),
        _env_path_check(config["comsol"]["mphserver_env"], False, "file"),
    ]


def _script_text(config: dict[str, Any]) -> str:
    model_tag = config["smoke_script"]["model_tag"]
    scalar_name = config["smoke_script"]["expected_scalar_name"]
    return "\n".join(
        [
            "% Generated by science-capability-registry COMSOL C01.",
            "% This script is a minimal LiveLink bridge smoke candidate.",
            "function comsol_c01_bridge_smoke()",
            "mliDir = getenv('COMSOL_MLI_DIR');",
            "if strlength(mliDir) > 0",
            "    addpath(mliDir);",
            "end",
            "import com.comsol.model.*",
            "import com.comsol.model.util.*",
            "host = getenv('COMSOL_SERVER_HOST');",
            "portText = getenv('COMSOL_SERVER_PORT');",
            "if strlength(host) > 0",
            "    if strlength(portText) > 0",
            "        mphstart(host, str2double(portText));",
            "    else",
            "        mphstart(host);",
            "    end",
            "end",
            f"model = ModelUtil.create('{model_tag}');",
            f"model.param.set('{scalar_name}', '1');",
            "fid = fopen('comsol_c01_scalar.txt', 'w');",
            f"fprintf(fid, '{scalar_name}=%0.15g\\n', 1.0);",
            "fclose(fid);",
            f"ModelUtil.remove('{model_tag}');",
            "end",
            "comsol_c01_bridge_smoke();",
            "",
        ]
    )


def _write_script(config: dict[str, Any], output_dir: Path) -> Path:
    script_path = output_dir / config["smoke_script"]["filename"]
    script_path.write_text(_script_text(config), encoding="ascii")
    return script_path


def _write_placeholders(output_dir: Path, message: str) -> None:
    for name in ["stdout.txt", "stderr.txt"]:
        (output_dir / name).write_text(message + "\n", encoding="utf-8")


def _execute_matlab(config: dict[str, Any], output_dir: Path, script_path: Path) -> int:
    matlab_exe = Path(os.environ[config["matlab"]["executable_env"]])
    stdout_path = output_dir / "stdout.txt"
    stderr_path = output_dir / "stderr.txt"
    script_expr = f"run('{script_path.resolve().as_posix()}')"
    with stdout_path.open("w", encoding="utf-8", errors="replace") as stdout, stderr_path.open(
        "w", encoding="utf-8", errors="replace"
    ) as stderr:
        result = subprocess.run(
            [str(matlab_exe), config["matlab"]["batch_argument"], script_expr],
            cwd=output_dir,
            stdout=stdout,
            stderr=stderr,
            timeout=float(config["backend"]["timeout_s"]),
            check=False,
        )
    return result.returncode


def _build_metrics(
    config: dict[str, Any],
    output_dir: Path,
    script_path: Path,
    environment_checks: list[dict[str, Any]],
    dry_run: bool,
    matlab_return_code: int | None,
) -> dict[str, Any]:
    scalar_file = output_dir / "comsol_c01_scalar.txt"
    finite_scalar = parse_scalar_file(scalar_file, config["smoke_script"]["expected_scalar_name"])
    env_summary = summarize_environment_checks(environment_checks)
    if dry_run:
        runtime_status = "dry_run_not_executed"
    elif config["backend"]["type"] == "preflight_only":
        runtime_status = "env_preflight_passed_no_matlab_execution" if env_summary["all_required_paths_exist"] else "blocked_by_runtime_profile"
    elif matlab_return_code is None:
        runtime_status = "blocked_by_runtime_profile"
    else:
        runtime_status = "matlab_executed"
    return {
        "capability_id": config["capability_id"],
        "case_id": config["case_id"],
        "validated_config": True,
        "script_generated": script_path.exists(),
        "script_file": script_path.name,
        "environment_checks": environment_checks,
        "environment_summary": env_summary,
        "matlab_executed": matlab_return_code is not None,
        "matlab_return_code": matlab_return_code,
        "scalar_file": scalar_file.name,
        "scalar_file_written": scalar_file.exists(),
        "finite_scalar": finite_scalar,
        "runtime_status": runtime_status,
    }


def _build_manifest(config: dict[str, Any], output_dir: Path, generated_files: list[str], metrics: dict[str, Any], validation: dict[str, Any]) -> dict[str, Any]:
    return {
        "capability_id": config["capability_id"],
        "case_id": config["case_id"],
        "source_config": config.get("_config_path"),
        "schema_id": SCHEMA_ID,
        "validated_config": True,
        "output_dir": str(output_dir),
        "runtime_profile": config["comsol"]["runtime_profile"],
        "runtime_profile_config": config["comsol"]["runtime_profile_config"],
        "backend": config["backend"],
        "generated_files": generated_files,
        "expected_outputs": config["outputs"]["expected_outputs"],
        "metrics": metrics,
        "validation": validation,
        "scope": validation["scope"],
    }


def run(
    config_path: str | Path | None = None,
    config: dict[str, Any] | None = None,
    output_dir: str | Path | None = None,
    dry_run: bool = False,
    backend: str | None = None,
) -> dict[str, Any]:
    if config is None:
        if config_path is None:
            raise ValueError("Either config_path or config must be provided.")
        config = load_case_config(config_path)
    else:
        config = validate_case_config(config)
    if backend is not None:
        config = {**config, "backend": {**config["backend"], "type": backend}}
        config = validate_case_config(config)

    output_path = Path(output_dir) if output_dir is not None else repo_relative_path(config["outputs"]["output_dir"])
    output_path.mkdir(parents=True, exist_ok=True)
    script_path = _write_script(config, output_path)
    environment_checks = _collect_environment(config)
    env_summary = summarize_environment_checks(environment_checks)
    matlab_return_code: int | None = None
    generated_files = [
        config["smoke_script"]["filename"],
        "stdout.txt",
        "stderr.txt",
        "metrics.json",
        "validation.json",
        "validation_report.md",
        "manifest.json",
    ]
    backend_type = config["backend"]["type"]
    if dry_run or backend_type == "dry_run_only":
        _write_placeholders(output_path, "dry-run placeholder; MATLAB and COMSOL were not executed.")
    elif backend_type == "preflight_only":
        _write_placeholders(output_path, "preflight-only placeholder; MATLAB and COMSOL were not executed.")
    elif backend_type == "matlab_livelink_smoke":
        if env_summary["all_required_paths_exist"]:
            matlab_return_code = _execute_matlab(config, output_path, script_path)
            if (output_path / "comsol_c01_scalar.txt").exists():
                generated_files.append("comsol_c01_scalar.txt")
        else:
            _write_placeholders(output_path, "runtime profile is incomplete; MATLAB and COMSOL were not executed.")
    else:
        raise NotImplementedError(f"COMSOL C01 backend {backend_type!r} is not implemented.")

    metrics = _build_metrics(config, output_path, script_path, environment_checks, dry_run, matlab_return_code)
    validation = validate_metrics(metrics, config, output_path, check_artifacts=False)
    (output_path / "metrics.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    (output_path / "validation.json").write_text(json.dumps(validation, indent=2), encoding="utf-8")
    write_validation_report(output_path / "validation_report.md", config, metrics, validation)
    manifest = _build_manifest(config, output_path, generated_files, metrics, validation)
    (output_path / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    validation = validate_metrics(metrics, config, output_path, check_artifacts=True)
    manifest["validation"] = validation
    manifest["scope"] = validation["scope"]
    (output_path / "validation.json").write_text(json.dumps(validation, indent=2), encoding="utf-8")
    write_validation_report(output_path / "validation_report.md", config, metrics, validation)
    (output_path / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest


def run_from_config(config_path: str | Path, output_dir: str | Path | None = None) -> dict[str, Any]:
    return run(config_path=config_path, output_dir=output_dir, dry_run=True)
