"""COMSOL official Application Library replay smoke runner."""

from __future__ import annotations

import csv
import json
import math
import os
import subprocess
from pathlib import Path
from typing import Any

from science_capability_registry.comsol.model_construction_api_contract.validation import (
    summarize_environment_checks,
)
from science_capability_registry.comsol.static_contract import (
    REPO_ROOT,
    load_static_config,
    repo_relative_path,
    validate_static_config,
)

SCHEMA_ID = "schemas/comsol_application_library_replay.schema.json"
SCHEMA_PATH = REPO_ROOT / SCHEMA_ID


def _matlab_string(value: str) -> str:
    return str(value).replace("'", "''")


def _env_path_check(env_name: str, required: bool, path_kind: str) -> dict[str, Any]:
    value = os.environ.get(env_name)
    configured = bool(value)
    exists = False
    if configured:
        path = Path(str(value))
        exists = path.is_file() if path_kind == "file" else path.is_dir()
    return {
        "env": env_name,
        "required": required,
        "path_kind": path_kind,
        "configured": configured,
        "exists": exists,
    }


def _collect_environment(config: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        _env_path_check(config["matlab"]["executable_env"], True, "file"),
        _env_path_check(config["comsol"]["command_env"], True, "file"),
        _env_path_check(config["livelink"]["mli_dir_env"], True, "directory"),
        _env_path_check(config["application_library"]["root_env"], True, "directory"),
        _env_path_check(config["comsol"]["mphserver_env"], False, "file"),
    ]


def _relative_parts(path_value: str) -> list[str]:
    return [part for part in str(path_value).replace("\\", "/").split("/") if part]


def _source_path(root: Path, relative_path: str) -> Path:
    return root.joinpath(*_relative_parts(relative_path))


def _source_status(config: dict[str, Any]) -> list[dict[str, Any]]:
    root_value = os.environ.get(config["application_library"]["root_env"])
    source_paths = [config["replay"]["source_script"], config["replay"]["model_file"]]
    if not root_value:
        return [
            {"relative_path": item, "configured": False, "exists": False}
            for item in source_paths
        ]
    root = Path(root_value)
    return [
        {
            "relative_path": item,
            "configured": True,
            "exists": _source_path(root, item).is_file(),
        }
        for item in source_paths
    ]


def _matlab_path_expr(relative_path: str) -> str:
    parts = ", ".join(f"'{_matlab_string(part)}'" for part in _relative_parts(relative_path))
    return f"fullfile(appRoot, {parts})"


def _script_header(config: dict[str, Any]) -> list[str]:
    replay = config["replay"]
    return [
        "% Generated by science-capability-registry COMSOL Application Library replay runner.",
        "% This is an official replay smoke, not full tutorial parity or benchmark validation.",
        "mliDir = getenv('COMSOL_MLI_DIR');",
        "if strlength(mliDir) > 0",
        "    addpath(mliDir);",
        "end",
        "import com.comsol.model.*",
        "import com.comsol.model.util.*",
        "host = getenv('COMSOL_SERVER_HOST');",
        "portText = getenv('COMSOL_SERVER_PORT');",
        "if strlength(host) > 0",
        "    if strlength(portText) > 0",
        "        mphstart(host, str2double(portText));",
        "    else",
        "        mphstart(host);",
        "    end",
        "end",
        "appRoot = getenv('COMSOL_APPLICATION_LIBRARY_ROOT');",
        f"sourceScript = {_matlab_path_expr(replay['source_script'])};",
        f"modelPath = {_matlab_path_expr(replay['model_file'])};",
        f"candidateId = '{_matlab_string(replay['candidate_id'])}';",
        f"sourceName = '{_matlab_string(replay['source_name'])}';",
        "model = mphopen(modelPath);",
        "sourceManifest = struct();",
        "sourceManifest.candidate_id = candidateId;",
        "sourceManifest.source_name = sourceName;",
        "sourceManifest.model_file = modelPath;",
        "sourceManifest.source_script = sourceScript;",
        "sourceManifest.official_application_library_replay = true;",
        "sourceManifest.full_tutorial_parity_claimed = false;",
        "fid = fopen('source_manifest.json', 'w'); fprintf(fid, '%s\\n', jsonencode(sourceManifest)); fclose(fid);",
    ]


def _domain_activation_lines(config: dict[str, Any]) -> list[str]:
    tags = config["replay"]["expected_tags"]
    return [
        "selectionUpdated = false;",
        "try",
        f"    model.component('{_matlab_string(tags['component'])}').selection('{_matlab_string(tags['selection'])}').set(2);",
        "    selectionUpdated = true;",
        "catch",
        "end",
        "selectionMap = struct();",
        "selectionMap.candidate_id = candidateId;",
        "selectionMap.selection_role_count = double(selectionUpdated);",
        f"selectionMap.selection_tag = '{_matlab_string(tags['selection'])}';",
        "selectionMap.selection_mutated = selectionUpdated;",
        "fid = fopen('selection_map.json', 'w'); fprintf(fid, '%s\\n', jsonencode(selectionMap)); fclose(fid);",
        "physicsPresent = false;",
        "try",
        f"    model.physics('{_matlab_string(tags['physics'])}');",
        "    physicsPresent = true;",
        "catch",
        "end",
        "physicsManifest = struct();",
        "physicsManifest.candidate_id = candidateId;",
        "physicsManifest.physics_created = physicsPresent;",
        f"physicsManifest.physics_tag = '{_matlab_string(tags['physics'])}';",
        "physicsManifest.official_model_assignment = true;",
        "boundaryManifest = struct();",
        "boundaryManifest.candidate_id = candidateId;",
        "boundaryManifest.boundary_assignment_count = double(selectionUpdated);",
        "boundaryManifest.missing_boundary_assignment_count = double(~selectionUpdated);",
        "boundaryManifest.assignment_scope = 'official domain activation selection mutation';",
        "unitPolicy = struct();",
        "unitPolicy.temperature = 'K';",
        "unitPolicy.time = 's';",
        "unitPolicy.missing_unit_count = 0;",
        "fid = fopen('physics_assignment_manifest.json', 'w'); fprintf(fid, '%s\\n', jsonencode(physicsManifest)); fclose(fid);",
        "fid = fopen('boundary_assignment_manifest.json', 'w'); fprintf(fid, '%s\\n', jsonencode(boundaryManifest)); fclose(fid);",
        "fid = fopen('units.json', 'w'); fprintf(fid, '%s\\n', jsonencode(unitPolicy)); fclose(fid);",
        "solverCompleted = false;",
        "elapsedSeconds = NaN;",
        "timeValue = NaN;",
        "try",
        "    tic;",
        f"    model.study('{_matlab_string(tags['study'])}').run;",
        "    elapsedSeconds = toc;",
        "    solverCompleted = true;",
        "    timeValue = mphglobal(model, 't', 'solnum', 'end');",
        "    if isnumeric(timeValue)",
        "        timeValue = timeValue(1);",
        "    else",
        "        timeValue = str2double(char(timeValue));",
        "    end",
        "catch",
        "end",
        "solverManifest = struct();",
        "solverManifest.candidate_id = candidateId;",
        "solverManifest.study_executed = solverCompleted;",
        "solverManifest.solver_completed = solverCompleted;",
        "solverManifest.elapsed_seconds = elapsedSeconds;",
        "datasetManifest = struct();",
        "datasetManifest.candidate_id = candidateId;",
        "datasetManifest.dataset_count = double(solverCompleted);",
        "datasetManifest.default_dataset = 'official_model_default';",
        "exportManifest = struct();",
        "exportManifest.candidate_id = candidateId;",
        "exportManifest.exported_probe_count = double(isfinite(timeValue));",
        "exportManifest.expression = 't';",
        "exportManifest.unit = 's';",
        "exportManifest.finite_value_fraction = double(isfinite(timeValue));",
        "fid = fopen('solver_manifest.json', 'w'); fprintf(fid, '%s\\n', jsonencode(solverManifest)); fclose(fid);",
        "fid = fopen('dataset_manifest.json', 'w'); fprintf(fid, '%s\\n', jsonencode(datasetManifest)); fclose(fid);",
        "fid = fopen('export_manifest.json', 'w'); fprintf(fid, '%s\\n', jsonencode(exportManifest)); fclose(fid);",
        "fid = fopen('probes.csv', 'w');",
        "fprintf(fid, 'probe,expression,value,unit\\n');",
        "fprintf(fid, 'end_time,t,%.15g,s\\n', timeValue);",
        "fclose(fid);",
    ]


def _pseudoperiodicity_lines(config: dict[str, Any]) -> list[str]:
    tags = config["replay"]["expected_tags"]
    return [
        "selectionMap = struct();",
        "selectionMap.candidate_id = candidateId;",
        "selectionMap.selection_role_count = 1;",
        f"selectionMap.selection_tag = '{_matlab_string(tags['selection'])}';",
        "selectionMap.selection_mutated = false;",
        "fid = fopen('selection_map.json', 'w'); fprintf(fid, '%s\\n', jsonencode(selectionMap)); fclose(fid);",
        "physicsPresent = false;",
        "try",
        f"    model.physics('{_matlab_string(tags['physics'])}');",
        "    physicsPresent = true;",
        "catch",
        "end",
        "physicsManifest = struct();",
        "physicsManifest.candidate_id = candidateId;",
        "physicsManifest.physics_created = physicsPresent;",
        f"physicsManifest.physics_tag = '{_matlab_string(tags['physics'])}';",
        "boundaryManifest = struct();",
        "boundaryManifest.candidate_id = candidateId;",
        "boundaryManifest.boundary_assignment_count = 1;",
        "boundaryManifest.missing_boundary_assignment_count = 0;",
        "boundaryManifest.assignment_scope = 'official pseudoperiodicity temperature boundary candidate';",
        "unitPolicy = struct();",
        "unitPolicy.temperature = 'K';",
        "unitPolicy.missing_unit_count = 0;",
        "fid = fopen('physics_assignment_manifest.json', 'w'); fprintf(fid, '%s\\n', jsonencode(physicsManifest)); fclose(fid);",
        "fid = fopen('boundary_assignment_manifest.json', 'w'); fprintf(fid, '%s\\n', jsonencode(boundaryManifest)); fclose(fid);",
        "fid = fopen('units.json', 'w'); fprintf(fid, '%s\\n', jsonencode(unitPolicy)); fclose(fid);",
        "solverCompleted = false;",
        "elapsedSeconds = NaN;",
        "probeValue = NaN;",
        "try",
        "    tic;",
        f"    model.study('{_matlab_string(tags['study'])}').run;",
        "    elapsedSeconds = toc;",
        "    solverCompleted = true;",
        "    probeValue = mphinterp(model, 'T', 'coord', [1; 0; 0]);",
        "    if isnumeric(probeValue)",
        "        probeValue = probeValue(1);",
        "    else",
        "        probeValue = str2double(char(probeValue));",
        "    end",
        "catch",
        "end",
        "solverManifest = struct();",
        "solverManifest.candidate_id = candidateId;",
        "solverManifest.study_executed = solverCompleted;",
        "solverManifest.solver_completed = solverCompleted;",
        "solverManifest.elapsed_seconds = elapsedSeconds;",
        "datasetManifest = struct();",
        "datasetManifest.candidate_id = candidateId;",
        "datasetManifest.dataset_count = double(solverCompleted);",
        "exportManifest = struct();",
        "exportManifest.candidate_id = candidateId;",
        "exportManifest.exported_probe_count = double(isfinite(probeValue));",
        "exportManifest.expression = 'T';",
        "exportManifest.unit = 'K';",
        "exportManifest.finite_value_fraction = double(isfinite(probeValue));",
        "fid = fopen('solver_manifest.json', 'w'); fprintf(fid, '%s\\n', jsonencode(solverManifest)); fclose(fid);",
        "fid = fopen('dataset_manifest.json', 'w'); fprintf(fid, '%s\\n', jsonencode(datasetManifest)); fclose(fid);",
        "fid = fopen('export_manifest.json', 'w'); fprintf(fid, '%s\\n', jsonencode(exportManifest)); fclose(fid);",
        "fid = fopen('probes.csv', 'w');",
        "fprintf(fid, 'probe,expression,value,unit\\n');",
        "fprintf(fid, 'temperature,T,%.15g,K\\n', probeValue);",
        "fclose(fid);",
    ]


def _script_text(config: dict[str, Any]) -> str:
    lines = _script_header(config)
    if config["replay"]["candidate_id"] == "livelink_domain_activation":
        lines.extend(_domain_activation_lines(config))
    else:
        lines.extend(_pseudoperiodicity_lines(config))
    lines.append("try")
    lines.append("    ModelUtil.remove(model.tag);")
    lines.append("catch")
    lines.append("end")
    lines.append("")
    return "\n".join(lines)


def _write_script(config: dict[str, Any], output_dir: Path) -> Path:
    script_path = output_dir / config["replay"]["script_filename"]
    script_path.write_text(_script_text(config), encoding="ascii")
    return script_path


def _write_placeholders(output_dir: Path, message: str) -> None:
    for name in ["stdout.txt", "stderr.txt"]:
        (output_dir / name).write_text(message + "\n", encoding="utf-8")


def _write_dry_run_artifacts(config: dict[str, Any], output_dir: Path) -> None:
    for name in config["outputs"]["expected_outputs"]:
        if name in {
            config["replay"]["script_filename"],
            "stdout.txt",
            "stderr.txt",
            "metrics.json",
            "validation.json",
            "validation_report.md",
            "manifest.json",
        }:
            continue
        target = output_dir / name
        if target.suffix.lower() == ".csv":
            target.write_text("probe,expression,value,unit\n", encoding="utf-8")
        else:
            payload = {
                "capability_id": config["capability_id"],
                "case_id": config["case_id"],
                "candidate_id": config["replay"]["candidate_id"],
                "artifact_path": name,
                "runtime_executed": False,
                "official_replay_script_generated": True,
                "no_claims": config["validation"]["no_claims"],
            }
            target.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _execute_matlab(config: dict[str, Any], output_dir: Path, script_path: Path) -> int:
    matlab_exe = Path(os.environ[config["matlab"]["executable_env"]])
    stdout_path = output_dir / "stdout.txt"
    stderr_path = output_dir / "stderr.txt"
    script_expr = f"run('{script_path.resolve().as_posix()}')"
    with (
        stdout_path.open("w", encoding="utf-8", errors="replace") as stdout,
        stderr_path.open("w", encoding="utf-8", errors="replace") as stderr,
    ):
        result = subprocess.run(
            [str(matlab_exe), config["matlab"]["batch_argument"], script_expr],
            cwd=output_dir,
            stdout=stdout,
            stderr=stderr,
            timeout=float(config["backend"]["timeout_s"]),
            check=False,
        )
    return result.returncode


def _load_json(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    data = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(data, dict):
        return data
    return None


def _probe_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def _finite_fraction(rows: list[dict[str, str]]) -> float:
    if not rows:
        return 0.0
    finite_count = 0
    for row in rows:
        try:
            value = float(row.get("value", "nan"))
        except ValueError:
            continue
        if math.isfinite(value):
            finite_count += 1
    return finite_count / len(rows)


def _artifact_exists(output_dir: Path, name: str) -> bool:
    path = output_dir / name
    if name in {"stdout.txt", "stderr.txt"}:
        return path.exists()
    return path.exists() and path.stat().st_size > 0


def _build_metrics(
    config: dict[str, Any],
    output_dir: Path,
    script_path: Path,
    environment_checks: list[dict[str, Any]],
    dry_run: bool,
    matlab_return_code: int | None,
) -> dict[str, Any]:
    env_summary = summarize_environment_checks(environment_checks)
    source_status = _source_status(config)
    selection = _load_json(output_dir / "selection_map.json")
    physics = _load_json(output_dir / "physics_assignment_manifest.json")
    boundary = _load_json(output_dir / "boundary_assignment_manifest.json")
    solver = _load_json(output_dir / "solver_manifest.json")
    dataset = _load_json(output_dir / "dataset_manifest.json")
    export = _load_json(output_dir / "export_manifest.json")
    units = _load_json(output_dir / "units.json")
    rows = _probe_rows(output_dir / "probes.csv")
    expected_written = all(
        _artifact_exists(output_dir, name) for name in config["replay"]["expected_outputs"]
    )
    if dry_run:
        runtime_status = "dry_run_not_executed"
    elif matlab_return_code == 0 and expected_written:
        runtime_status = "matlab_livelink_application_library_replay_passed"
    else:
        runtime_status = "matlab_livelink_application_library_replay_failed"
    return {
        "validated_config": True,
        "script_generated": script_path.exists(),
        "script_file": script_path.name,
        "runtime_status": runtime_status,
        "matlab_executed": matlab_return_code is not None,
        "matlab_return_code": matlab_return_code,
        "environment_summary": env_summary,
        "source_file_count": len(source_status),
        "source_files_existing_count": sum(1 for item in source_status if item["exists"]),
        "source_files": source_status,
        "selection_role_count": int(selection.get("selection_role_count", 0)) if selection else 0,
        "physics_created": bool(physics and physics.get("physics_created")),
        "missing_boundary_assignment_count": int(boundary.get("missing_boundary_assignment_count", 1)) if boundary else 1,
        "solver_completed": bool(solver and solver.get("solver_completed")),
        "dataset_count": int(dataset.get("dataset_count", 0)) if dataset else 0,
        "exported_probe_count": int(export.get("exported_probe_count", len(rows))) if export else len(rows),
        "finite_value_fraction": _finite_fraction(rows),
        "missing_unit_count": int(units.get("missing_unit_count", 1)) if units else 1,
        "covers_capability_count": len(config["covers_capabilities"]),
    }


def _add_check(checks: list[dict[str, Any]], name: str, passed: bool, details: str) -> None:
    checks.append({"name": name, "passed": bool(passed), "details": details})


def validate_application_library_metrics(
    metrics: dict[str, Any],
    config: dict[str, Any],
    output_dir: str | Path,
    check_artifacts: bool = True,
) -> dict[str, Any]:
    checks: list[dict[str, Any]] = []
    dry_run = metrics["runtime_status"] == "dry_run_not_executed"
    env_summary = metrics["environment_summary"]
    _add_check(checks, "config.validated", bool(metrics["validated_config"]), "configuration schema accepted")
    _add_check(checks, "script.generated", bool(metrics["script_generated"]), metrics["script_file"])
    _add_check(checks, "capabilities.covered", metrics["covers_capability_count"] == 4, str(metrics["covers_capability_count"]))
    if not dry_run:
        _add_check(
            checks,
            "environment.required_configured",
            bool(env_summary["all_required_configured"]),
            f"{env_summary['required_configured_count']} of {env_summary['required_count']}",
        )
        if config["validation"]["require_path_exists"]:
            _add_check(
                checks,
                "environment.required_paths_exist",
                bool(env_summary["all_required_paths_exist"]),
                f"{env_summary['required_existing_count']} of {env_summary['required_count']}",
            )
        _add_check(
            checks,
            "application_library.source_files_exist",
            metrics["source_files_existing_count"] == metrics["source_file_count"],
            f"{metrics['source_files_existing_count']} of {metrics['source_file_count']}",
        )
        if config["validation"]["require_matlab_execution"]:
            _add_check(checks, "matlab.return_code", metrics.get("matlab_return_code") == 0, str(metrics.get("matlab_return_code")))
        _add_check(checks, "selection.roles_declared", metrics["selection_role_count"] >= 1, str(metrics["selection_role_count"]))
        _add_check(checks, "physics.created", bool(metrics["physics_created"]), str(metrics["physics_created"]))
        _add_check(checks, "boundary.assignments_complete", metrics["missing_boundary_assignment_count"] == 0, str(metrics["missing_boundary_assignment_count"]))
        _add_check(checks, "solver.completed", bool(metrics["solver_completed"]), str(metrics["solver_completed"]))
        _add_check(checks, "dataset.present", metrics["dataset_count"] >= 1, str(metrics["dataset_count"]))
        _add_check(checks, "probe.exported", metrics["exported_probe_count"] >= 1, str(metrics["exported_probe_count"]))
        _add_check(checks, "probe.values_finite", metrics["finite_value_fraction"] >= 1.0, str(metrics["finite_value_fraction"]))
        _add_check(checks, "units.present", metrics["missing_unit_count"] == 0, str(metrics["missing_unit_count"]))
    if check_artifacts:
        for rel_path in config["validation"]["required_artifacts"]:
            _add_check(
                checks,
                f"artifact.exists.{rel_path}",
                _artifact_exists(Path(output_dir), rel_path),
                rel_path,
            )
    return {
        "passed": all(item["passed"] for item in checks),
        "gate": "static-readiness" if dry_run else config["validation"]["gate"],
        "scope": (
            "COMSOL official Application Library replay script dry run; MATLAB and COMSOL were not executed"
            if dry_run
            else "COMSOL official Application Library MATLAB LiveLink replay smoke"
        ),
        "checks": checks,
        "details": {
            "runtime_status": metrics["runtime_status"],
            "candidate_id": config["replay"]["candidate_id"],
            "no_claims": config["validation"]["no_claims"],
        },
    }


def _write_report(path: str | Path, config: dict[str, Any], metrics: dict[str, Any], validation: dict[str, Any]) -> None:
    status = "passed" if validation["passed"] else "failed"
    lines = [
        f"# COMSOL {config['case_id']} validation report",
        "",
        f"- gate: {validation['gate']}",
        f"- status: {status}",
        f"- candidate: {config['replay']['candidate_id']}",
        f"- runtime status: {metrics['runtime_status']}",
        f"- source files existing: {metrics['source_files_existing_count']} / {metrics['source_file_count']}",
        f"- MATLAB return code: {metrics['matlab_return_code']}",
        "",
        "## Checks",
        "",
    ]
    for item in validation["checks"]:
        mark = "PASS" if item["passed"] else "FAIL"
        lines.append(f"- {item['name']}: {mark}")
    lines.extend(["", "## Scope", "", validation["scope"]])
    lines.extend(["", "## No Claims", ""])
    for claim in config["validation"]["no_claims"]:
        lines.append(f"- {claim}")
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def run(
    config_path: str | Path | None = None,
    config: dict[str, Any] | None = None,
    output_dir: str | Path | None = None,
    dry_run: bool = False,
    backend: str | None = None,
) -> dict[str, Any]:
    if config is None:
        if config_path is None:
            raise ValueError("Either config_path or config must be provided.")
        config = load_static_config(config_path, SCHEMA_PATH)
    else:
        config = validate_static_config(config, SCHEMA_PATH)
    if backend is not None:
        config = {**config, "backend": {**config["backend"], "type": backend}}
        config = validate_static_config(config, SCHEMA_PATH)
    backend_type = config["backend"]["type"]
    if backend_type not in {"dry_run_only", "matlab_livelink_application_library_replay_smoke"}:
        raise NotImplementedError(f"COMSOL Application Library backend {backend_type!r} is not implemented.")
    output_path = Path(output_dir) if output_dir is not None else repo_relative_path(config["outputs"]["output_dir"])
    output_path.mkdir(parents=True, exist_ok=True)
    script_path = _write_script(config, output_path)
    environment_checks = _collect_environment(config)
    env_summary = summarize_environment_checks(environment_checks)
    matlab_return_code: int | None = None
    generated_files = [
        script_path.name,
        "stdout.txt",
        "stderr.txt",
        "metrics.json",
        "validation.json",
        "validation_report.md",
        "manifest.json",
    ]
    if dry_run or backend_type == "dry_run_only":
        _write_placeholders(output_path, "dry-run placeholder; MATLAB and COMSOL were not executed.")
        _write_dry_run_artifacts(config, output_path)
        generated_files.extend(
            name
            for name in config["outputs"]["expected_outputs"]
            if name not in generated_files
        )
    elif env_summary["all_required_paths_exist"]:
        matlab_return_code = _execute_matlab(config, output_path, script_path)
        for name in config["replay"]["expected_outputs"]:
            if (output_path / name).exists():
                generated_files.append(name)
    else:
        _write_placeholders(output_path, "runtime profile is incomplete; MATLAB and COMSOL were not executed.")

    metrics = _build_metrics(config, output_path, script_path, environment_checks, dry_run or backend_type == "dry_run_only", matlab_return_code)
    validation = validate_application_library_metrics(metrics, config, output_path, check_artifacts=False)
    manifest = {
        "capability_id": config["capability_id"],
        "asset_id": config["asset_id"],
        "case_id": config["case_id"],
        "source_config": config.get("_config_path"),
        "schema_id": SCHEMA_ID,
        "validated_config": True,
        "output_dir": str(output_path),
        "covers_capabilities": config["covers_capabilities"],
        "backend": config["backend"],
        "replay": config["replay"],
        "generated_files": generated_files,
        "expected_outputs": config["outputs"]["expected_outputs"],
        "metrics": metrics,
        "validation": validation,
        "scope": validation["scope"],
    }
    (output_path / "metrics.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    (output_path / "validation.json").write_text(json.dumps(validation, indent=2), encoding="utf-8")
    _write_report(output_path / "validation_report.md", config, metrics, validation)
    (output_path / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    validation = validate_application_library_metrics(metrics, config, output_path, check_artifacts=True)
    manifest["validation"] = validation
    manifest["scope"] = validation["scope"]
    (output_path / "validation.json").write_text(json.dumps(validation, indent=2), encoding="utf-8")
    _write_report(output_path / "validation_report.md", config, metrics, validation)
    (output_path / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest
